name: Lucian Marin
description: Information Architect
url: http://iamlucian.ro

relative_permalinks: false
permalink: :title.html
markdown: redcarpet
highlighter: null
pygments: null

exclude: [readme.md]
include: [.htaccess]